blog/urls.py
from django.urls import path
from blog.views import PostView, CommentView, PostDetail


app_name = "blogs"

urlpatterns = [
    path("", PostView.as_view(), name="posts"),
    path("<int:pk>/post/", PostDetail.as_view(), name="detail"),
    path("<int:pk>/comment/", CommentView.as_view(), name="comment")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("shop/", include("shop.urls")),
    path("blog/", include("blog.urls")),
    path("", include("pages.urls")),
    path("users/", include("users.urls")),
    path("orders/", include('orders.urls'))
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path 
from pages.views import HomePage, ContacView


app_name = 'pages'

urlpatterns = [
    path("", HomePage.as_view(), name='home'),
    path("contact/", ContacView.as_view(), name='contact'),
]   

shop/urls.py
from django.urls import path
from shop.views import Shop, ProductDetail, WishlistView, update_cart_view, ShoppingCart, wishlist_view

app_name = "shop"

urlpatterns = [
    path("", Shop.as_view(), name="home"),
    path("product/<int:pk>", ProductDetail.as_view(), name="detail"),
    path("product/<int:pk>/wishlist/", wishlist_view, name="wishlist"),
    path("wishlist/", WishlistView.as_view(), name='all_wishlist'),
    path("add_cart/<int:id>/", update_cart_view, name="cart"),
    path("shopping_cart/", ShoppingCart.as_view(), name="shopping_cart" )

]

users/urls.py
from django.urls import  path
from users.views import logout_veiw, login_view, user_registration, ProfileView


app_name = 'user'


urlpatterns = [
    path("profile/", ProfileView.as_view(), name='profile'),
    path("logout/", logout_veiw, name='logout'),
    path("login/", login_view, name='login'),
    path("registration/", user_registration, name='registration')
]

templates/layouts/base-login.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login-style.css' %}">

    {% block extra_css %}

    {% endblock %}
</head>

<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>
<!-- Header Section End -->
{% block content %}

{% endblock %}


<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" action="{% url 'shop:home' %}" method="get">
            <input type="text" name="search" value="{{ request.GET.search }}" id="search-input"
                   placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}

{% endblock %}
</body>
</html>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css">
</head>

{% include "layouts/navbar.html"%}
<!-- navbar -->

{% block content %}

{% endblock %}

{% include "layouts/footer.html"%}


    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'js/mixitup.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

templates/layouts/footer.html
    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="img/footer-logo.png" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="img/payment.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Clothing Store</a></li>
                            <li><a href="#">Trending Shoes</a></li>
                            <li><a href="#">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivary</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>2020
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

templates/layouts/navbar.html
{% load static %}
{% load my_tags %}
{% load i18n %}
{% block extra_css %}
    <style>
        .my_lang:hover {
            background: #0b0b0b !important;
        }
        .my_lang:hover a{
            color: white !important;
        }
    </style>

{% endblock %}
<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="{% url 'user:login' %}">{% trans 'Sign in' %}</a>
        </div>
        <div class="offcanvas__top__hover">
            {% get_current_language as LANGUAGE_CODE %}

            <span>{{ LANGUAGE_CODE }} <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>EN</li>
                <li>UZ</li>
                <li>RU</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                                <a href="">{% trans 'Order History' %}</a>
                                <a href="{% url 'user:profile' %}">{% trans 'Profile' %}</a>
                                <a href="{% url 'user:logout' %}">{% trans 'Log out' %}</a>
                            {% else %}
                                <a href="{% url 'user:login' %}">{% trans 'Sign in' %}</a>
                            {% endif %}
                        </div>
                        <div class="header__top__hover">
                            <span>{{ LANGUAGE_CODE }} <i class="arrow_carrot-down"></i></span>
                            {% get_available_languages as LANGUAGES %}

                            <ul>
                                {% for lang in LANGUAGES %}
                                    {% if lang.0 != LANGUAGE_CODE %}
                                        <li class="my_lang">
                                            <a href="/{{ lang.0 }}/{{ request.path|slice:"4:" }}" class="text-dark">
                                                {{ lang.0|upper }}
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        {% url 'pages:home' as current_link %}
                        <li class="{% if request.path == current_link %}active{% endif %}"><a
                                href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                        {% url 'shop:home' as current_link %}
                        <li class="{% if request.path == current_link %}active{% endif %}">
                            <a href="{% url 'shop:home' %}">Shop</a>
                        </li>
                        {% url 'blogs:posts' as current_link %}
                        <li class="{% if request.path == current_link %}active{% endif %}"><a
                                href="{% url 'blogs:posts' %}">{% trans 'Blog' %}</a></li>
                        {% url 'pages:contact' as current_link %}
                        <li class="{% if request.path == current_link %}active{% endif %}"><a
                                href="{% url 'pages:contact' %}">{% trans 'Contacts' %}</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'shop:all_wishlist' %}"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    {% endif %}
                    {% comment %}
                         {% cart_info request as info %}
                    {% endcomment %}
                    <a href="{% url 'shop:shopping_cart' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>{{ info.0 }}</span></a>
                    <div class="price">${{ info.1 }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->