blog/urls.py
from django.urls import path
from blog.views import PostView, CommentView, PostDetail


app_name = "blogs"

urlpatterns = [
    path("", PostView.as_view(), name="posts"),
    path("<int:pk>/post/", PostDetail.as_view(), name="detail"),
    path("<int:pk>/comment/", CommentView.as_view(), name="comment")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("shop/", include("shop.urls")),
    path("blog/", include("blog.urls")),
    path("", include("pages.urls")),
    path("users/", include("users.urls")),
    path("orders/", include('orders.urls'))
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import  path
from orders.views import OrderHistoryView, CheckoutView

app_name = 'orders'


urlpatterns = [
    path("order/history/", OrderHistoryView.as_view(), name='history'),
    path("checkout/", CheckoutView.as_view(), name='checkout')
]

pages/urls.py
from django.urls import path 
from pages.views import HomePage, ContacView


app_name = 'pages'

urlpatterns = [
    path("", HomePage.as_view(), name='home'),
    path("contact/", ContacView.as_view(), name='contact'),
]   

shop/urls.py
from django.urls import path
from shop.views import Shop, ProductDetail, WishlistView, update_cart_view, ShoppingCart, wishlist_view

app_name = "shop"

urlpatterns = [
    path("", Shop.as_view(), name="home"),
    path("product/<int:pk>", ProductDetail.as_view(), name="detail"),
    path("product/<int:pk>/wishlist/", wishlist_view, name="wishlist"),
    path("wishlist/", WishlistView.as_view(), name='all_wishlist'),
    path("add_cart/<int:id>/", update_cart_view, name="cart"),
    path("shopping_cart/", ShoppingCart.as_view(), name="shopping_cart" )

]

users/urls.py
from django.urls import  path
from users.views import logout_veiw, login_view, user_registration, ProfileView


app_name = 'user'


urlpatterns = [
    path("profile/", ProfileView.as_view(), name='profile'),
    path("logout/", logout_veiw, name='logout'),
    path("login/", login_view, name='login'),
    path("registration/", user_registration, name='registration')
]

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from shop.abstract import BaseModel


class Author(models.Model):
    full_name = models.CharField(max_length=100, verbose_name=_("full name"))
    image = models.ImageField(upload_to="author_image/", verbose_name=_("image"))


    class Meta:
        verbose_name=_("Author")
        verbose_name_plural = _("Authors")


    def __str__(self) -> str:
        return self.full_name
    

class PostTag(BaseModel):
    name = models.CharField(max_length=30, verbose_name=_("name"))

    class Meta:
        verbose_name=_("Tag")
        verbose_name_plural=_("Tags")


    def __str__(self) -> str:
        return self.name
    

class Post(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_("title"))
    body = models.TextField(verbose_name=_("body"))
    main_image=models.ImageField(upload_to="post_image/", verbose_name=_("main image"))
    author = models.ForeignKey(Author, related_name="posts", on_delete=models.RESTRICT)
    tag = models.ManyToManyField(PostTag, related_name="posts", verbose_name=_("tag"))



    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    def __str__(self) -> str:
        return f"{self.title[:100]} ..." 
    

class Comment(BaseModel):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    email = models.EmailField(verbose_name=_("email"))
    phone = models.CharField(max_length=13, verbose_name=_("phone"))
    comment = models.TextField(verbose_name=_("comment"))
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name=_("post"))


    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")


    def __str__(self) -> str:
        return f"{self.name}\n{self.email}\n{self.phone}\n{self.comment[:50]}..."
    
    

shop/models.py
from django.db import models, IntegrityError
from django.contrib.auth import get_user_model
from django.db.models import Sum
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from shop.abstract import BaseModel

UserModel = get_user_model()


class Category(BaseModel):
    name = models.CharField(max_length=60, verbose_name=_("name"))


    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = "Product category"
        verbose_name = "Category"
        verbose_name_plural = "2. Categories"


class ProductTag(BaseModel):
    name = models.CharField(max_length=60, verbose_name=_("name"))


    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = "Product tag"
        verbose_name = "Tag"
        verbose_name_plural = "6. Tags"


class BrandModel(BaseModel):
    name = models.CharField(max_length=60, verbose_name=_("name"))

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = "Product brand"
        verbose_name = "Brand"
        verbose_name_plural = "3. Brands"


class SizeModel(BaseModel):
    name = models.CharField(max_length=60, verbose_name=_("name"))

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = "Product size"
        verbose_name = "Size"
        verbose_name_plural = "4. Sizes"


class ColorModel(BaseModel):
    code = models.CharField(max_length=60, verbose_name=_("name"))

    def __str__(self) -> str:
        return self.code 
    
    class Meta:
        db_table = "Product color"
        verbose_name = "Color"
        verbose_name_plural = "5. Colors"


class ProductModel(BaseModel):
    title = models.CharField(max_length=60, verbose_name=_("title"))
    short_description = models.CharField(max_length=255, verbose_name=_("short description"))
    long_description = models.TextField(verbose_name=_("long description"))
    price = models.FloatField(verbose_name=_("price"))
    real_price = models.FloatField(verbose_name=_("real price"), default=0)
    sale = models.BooleanField(verbose_name=_("sale"), default=False)
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_("discount"))
    main_image = models.ImageField(upload_to="media/shop_product/%Y/%m/%d", verbose_name=_("main image"))
    category = models.ForeignKey(
        Category,
        on_delete=models.RESTRICT,
        related_name="products",
        verbose_name=_("category")
    )
    tags = models.ManyToManyField(
        ProductTag,
        related_name="products",
        verbose_name=_("tags")
    )
    sizes = models.ManyToManyField(
        SizeModel,
        related_name="products",
        verbose_name=_("sizes")
    )
    colors = models.ManyToManyField(
        ColorModel,
        related_name="products",
        verbose_name=_("colors")
    )
    brand = models.ForeignKey(
        BrandModel,
        on_delete=models.RESTRICT,
        related_name="products",
        verbose_name=_("brand"),
        null=True
    )

    class Meta:
        db_table = "Shop product"
        verbose_name = "Product"
        verbose_name_plural = "1. Products"


    def is_discount(self):
        return bool(self.discount)
    
    def new(self):
        return (timezone.now() - self.created_at).days <= 7
    
    @staticmethod
    def get_cart_info(self):
        cart = request.session.get("cart", [])#[67.4]
        if not cart:
            return 0, 0.0
        return len(cart), ProductModel.objects.filter(id__in=cart).aggregate(Sum("real_price"))['real_price__sum']
    
    @staticmethod
    def get_cart_objects(self):
        cart = request.session.get("cart", [])
        if not cart:
            return None
        return ProductModel.objects.filter(id__in=cart)

    

class Wishlist(BaseModel):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="wishlists", verbose_name=_("user"))
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, verbose_name=_("product"))    


    @staticmethod
    def created_or_delete(user, product):
        try:
            return Wishlist.objects.create(user=user, product=product)
        except IntegrityError:
            return Wishlist.objects.get(user=user, product=product)
        
    def __str__(self) -> str:
        return f"{self.user.get_full_name()} | {self.product.title}"
    

    class Meta:
        db_table = "Wishlist"
        verbose_name = "Wishlist"
        verbose_name_plural = "Wishlists"
        unique_together = "user", "product",

blog/forms.py
from django  import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['post', 'created_at']

shop/forms.py
from django import forms
from .models import ColorModel

class ColorForms(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={"type":"color"}))

    class Meta:
        model = ColorModel
        fields = "__all__"
        

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView, DetailView, CreateView
from blog.forms import CommentForm
from django.urls import reverse



class PostView(ListView):
    template_name = "blog.html"

    def get_queryset(self):
        qs = Post.objects.order_by("-id")
        tag = self.request.GET.get("tag")
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs


class PostDetail(DetailView):
    model = Post
    template_name = "blog-details.html"


class CommentView(CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        # print(form.instance)
        # form.instance.post = get_object_or_404(Post, pk=self.kwargs.get("pk"))
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse("blogs:detail", kwargs={"pk":self.kwargs.get("pk")}) #blog/details/3
    

shop/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min, Max
from django.views.generic import ListView, DetailView
from .models import ProductModel, Category, ProductTag, ColorModel, BrandModel, SizeModel, Wishlist



class ShoppingCart(ListView):
    template_name = "shopping-cart.html"

    def get_queryset(self):
        products = ProductModel.get_cart_objects(self.request)
        return products
    

class Shop(ListView):
    template_name = "shop.html"
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.all()

        search = self.request.GET.get("search")
        if search:
            qs = qs.filter(title__icontains=search)#__icontains

        
        cat = self.request.GET.get("cat")
        if cat:
            qs = qs.filter(category_id=cat)


        tag = self.request.GET.get("tag")
        if tag:
            qs = qs.filter(tags=tag)


        size = self.request.GET.get("size")
        if size:
            qs = qs.filter(sizes=size)



        color = self.request.GET.get("color")
        if color:
            qs = qs.filter(colors=color)


        brand = self.request.GET.get("brand")
        if brand:
            qs = qs.filter(brand_id=brand)


        sort = self.request.GET.get("sort")
        if sort == "price":
            qs = qs.order_by("price")
        elif sort == "-price":
            qs = qs.order_by("-price")
        elif sort == "sale":
            qs = qs.filter(sale=True)


        price = self.request.GET.get('price')
        if price:
            min, max = price.split(";")
            qs = qs.filter(real_price__gte=min, real_price__lte=max)#__gte/__lte


        return qs 
    

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(**kwargs)
        data['categories'] = Category.objects.all()
        data['tags'] = ProductTag.objects.all()
        data['sizes'] = SizeModel.objects.all()
        data['brands'] = BrandModel.objects.all()
        data['colors'] = ColorModel.objects.all()
        data['min_price'], data['max_price'] = ProductModel.objects.aggregate(Min("real_price"), Max("real_price")).values()
        return data
    



class ProductDetail(DetailView):
    model = ProductModel
    template_name = "shop-details.html"


    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['products'] = ProductModel.objects.all().exclude(id=self.object.pk)[:4]
        return data
    

@login_required
def wishlist_view(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    Wishlist.created_or_delete(request.user, product)
    return redirect(request.GET.get("next", '/'))


class WishlistView(LoginRequiredMixin, ListView):
    template_name = "wishlist.html"

    def get_queryset(self):
        return ProductModel.objects.filter(wishlistmodel__user_id=self.request.user)

def update_cart_view(request, id):
    cart = request.session.get("cart", [])

    if id in cart:
        cart.remove(id)

    else:
        cart.append(id)


    request.session['cart'] = cart 
    print(request.session['cart'])
    return redirect(request.GET.get("next", '/'))

templates/blog-details.html
{% extends 'layouts/base.html'%}
{% load static %}

{% block content %}
    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>{{ object.author.full_name }}</li>
                            <li>{{ object.created_at|date:"F d, Y" }}</li>
                            {% if object.comments.values %}
                                <li>{{object.comments.values.count }} Comments</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.main_image.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                      
                        <div class="blog__details__quote">
                            <i class="fa fa-quote-left"></i>
                            <p>“When designing an advertisement for a particular product many things should be
                                researched like where it should be displayed.”</p>
                            <h6>_ John Smith _</h6>
                        </div>
                        <div class="blog__details__text">
                            {{ object.body }}
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.author.image.url}}" alt="{{object.author.full_name}}">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.author.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for i in object.tag.values %}
                                            <a href="{% url 'blogs:posts'%}?tag={{ i.name }}">#{{i.name}}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">

                                {% if object.get_previous_by_created_at %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}" class="blog__details__btns__item">
                                        <p><span class="arrow_left"></span> Previous Pod</p>
                                        <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                    </a>
                                </div>
                                {% endif %}

                                {% if object.get_next_by_created_at %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}" class="blog__details__btns__item blog__details__btns__item--next">
                                        <p>Next Pod <span class="arrow_right"></span></p>
                                        <h5>{{ object.get_next_by_created_at.title }}</h5>
                                    </a>
                                </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="container">
                            {% for i in object.comments.values %}
                                <div class="row mb-3">
                                    <div class="col-6"><strong>{{ i.name }}</strong></div>
                                    <div class="col-6 text-right">{{ i.created_at|timesince }}</div>
                                    <div class="col-12 mt-2">
                                        <p>
                                            {{ i.comment }}
                                        </p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>


                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:comment' pk=object.pk%}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="text" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="comment" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->


{% endblock %}

templates/checkout.html
{% extends 'layouts/base.html' %}
{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Check Out</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home'%}">Home</a>
                            <a href="{% url 'shop:home'%}">Shop</a>
                            <span>Check Out</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <form action="#" method="post">
                    {% csrf_token %}
                    {{ form.errors }}
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="coupon__code">
                                <span class="icon_tag_alt">
                                </span>
                                Have a coupon?
                                <a href="#">Click here</a> to enter your code
                            </h6>
                            <h6 class="checkout__title">Billing Details</h6>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Fist Name<span>*</span></p>
                                        <input type="text" value="{{ profile.first_name }}" name="first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" value="{{ profile.last_name }}" name="last_name">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Country<span>*</span></p>
                                <input type="text" value="{{ profile.country}}" name="country">
                            </div>
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" placeholder="Street Address" class="checkout__input__add"
                                value="{{ profile.address1}}" name="address1">
                                <input type="text" placeholder="Apartment, suite, unite ect (optinal)"
                                value="{{ profile.address2}}" name="address2">
                            </div>
                            <div class="checkout__input">
                                <p>Town/City<span>*</span></p>
                                <input type="text" value="{{ profile.city}}" name="city">
                            </div>
                            <div class="checkout__input">
                                <p>Country/State<span>*</span></p>
                                <input type="text" value="{{ profile.state}}" name="state">
                            </div>
                            <div class="checkout__input">
                                <p>Postcode / ZIP<span>*</span></p>
                                <input type="text" value="{{ profile.zip_code }}" name="zip_code">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Phone<span>*</span></p>
                                        <input type="text" value="{{ profile.phone}}" name="phone">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="text" value="{{ profile.email}}" name="email">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4 class="order__title">Your order</h4>
                                <div class="checkout__order__products">Product <span>Total</span></div>
                                {% for product in products %}
                                <ul class="checkout__total__products">
                                    <li>{{ forloop.counter }}. {{product.title}}
                                        <span>$ {{product.real_price}}</span></li>

                                </ul>
                                {% endfor %}
                                <ul class="checkout__total__all">
                                    {% cart_info request as info %}
                                    <li>Total <span>${{ info.1}}</span></li>
                                </ul>

                                <a href="{% url 'orders:history' %}">
                                    <button type="submit" class="site-btn">PLACE ORDER</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

{% endblock %}

templates/login.html
{% extends 'layouts/base-login.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="d-md-flex half">
        <div class="bg" style="background-image: url({% static 'img/bg_1.jpg' %});"></div>
        <div class="contents">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="form-block mx-auto">
                            <div class="text-center mb-5">
                                <h3 class="text-uppercase">Login</h3>
                            </div>
                            <form action="#" method="post">
                                {% csrf_token %}
                                {% comment %}
                                    {{ form|crispy }}
                                {% endcomment %}
                                <div class="d-sm-flex mb-5 align-items-center">
                                    <span class="ml-auto"><a href="{% url 'user:registration' %}" class="forgot-pass">Registration</a></span>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <input type="submit" value="Log In" class="btn btn-block py-2 btn-primary">

                                <span class="text-center my-3 d-block">or</span>


                                <div class="">
                                    <a href="#" class="btn btn-block py-2 btn-facebook">
                                        <span class="icon-facebook mr-3"></span> Login with facebook
                                    </a>
                                    <a href="#" class="btn btn-block py-2 btn-google"><span
                                            class="icon-google mr-3"></span> Login with Google</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/product_item.html
{% load static %}



<div class="product__item sale">
    <div class="product__item__pic set-bg" data-setbg="{{ product.main_image.url}}">
        {% if product.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.new %}
            <span class="label">New</span>
        {% endif %}
        <ul class="product__hover">
            {% if request.user.is_authenticated %}
                {% if product|is_wishlist:request %}
                    <li>
                        <a href="{% url 'shop:wishlist' pk=product.pk %}?next={{request.path}}"><img src="{% static 'img/icon/heart.png'%}" alt=""></a>
                    </li>

                {% else %}
                <li>
                    <a href="{% url 'shop:wishlist' pk=product.pk %}?next={{request.path}}"><img src="{% static 'img/black_heart.jpg'%}" alt=""></a>
                </li>
                {% endif %}
            {% endif %}
            
            <li><a href="{% url 'shop:detail' pk=product.pk %}"><img src="{% static 'img/icon/search.png'%}" alt=""></a></li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        <a href="{% url 'shop:cart' id=product.pk%}?next={{request.path}}" class="add-cart">
            {% if product|is_cart:request%}
                -Remove From Cart
            {% else %}
                + Add To Cart
            {% endif %}
        
        </a>
        <div class="rating">
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ product.real_price }} {% if product.is_discount %}
            <del class="text-secondary">{{ product.price }}</del>{% endif %}
        </h5>
        <div class="product__color__select">
           {% for color in product.colors.all %}
                <label style="" for="{{ color.code }}">
                    <input type="radio" id="{{ color.code }}">
                </label>
            {% endfor %}
        </div>
    </div>
</div>